/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorInventario;
import modelo.Producto;
import java.util.ArrayList;

/**
 *
 * @author Administrador
 */
public class PantallaVentas extends javax.swing.JFrame {
    
    javax.swing.JButton botonMesaActual; // Recordará qué mesa estamos atendiendo
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaVentas.class.getName());

    /**
     * Creates new form PantallaVentas
     */
    public PantallaVentas() {
        initComponents();
        cargarProductosEnCombo();
    }
    
    public void configurarMesa(javax.swing.JButton botonMesa, String nombreMesa) {
     this.botonMesaActual = botonMesa;
        this.setTitle(nombreMesa); // Le dejamos solo el nombre limpio (Ej: "Mesa 1")
        this.botonMesaActual.setBackground(java.awt.Color.RED); 
        
        // ¡Llamamos al lector apenas se abre la ventana!
        cargarPedidoMesa(nombreMesa);
 }
    
    private void cargarProductosEnCombo() {
        jComboBox1.removeAllItems(); // Borramos los ítems por defecto
        
        ControladorInventario control = new ControladorInventario();
        ArrayList<Producto> lista = control.obtenerTodosLosProductos(); // Traemos los datos de MySQL
        
        for (Producto p : lista) {
            jComboBox1.addItem(p.getNombre()); // Metemos los nombres al desplegable
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio Unitario", "Cantidad", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("TOTAL: $ 0");

        jButton1.setText("COBRAR  / FACTURAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel2.setText("Producto");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Cantidad");

        jButton2.setText("Agregar a la cuenta");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Cambiar Cantidad");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Quitar Producto");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton9.setText("Volver a Mesas");
        jButton9.addActionListener(this::jButton9ActionPerformed);

        jButton5.setText("ENVIAR A COCINA");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(120, 120, 120)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(0, 650, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton9))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String productoSeleccionado = jComboBox1.getSelectedItem().toString();
        String cantidadTexto = jTextField1.getText();

        if (cantidadTexto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, escribe una cantidad.");
            return; 
        }

        try {
            int cantidadNueva = Integer.parseInt(cantidadTexto); 

            // 1. Buscamos el precio en el inventario
            controlador.ControladorInventario control = new controlador.ControladorInventario();
            java.util.ArrayList<modelo.Producto> lista = control.obtenerTodosLosProductos();
            double precioUnitario = 0;
            for (modelo.Producto p : lista) {
                if (p.getNombre().equals(productoSeleccionado)) {
                    precioUnitario = p.getPrecio();
                    break; 
                }
            }

            // 2. ¿En qué mesa estamos parados?
            String nombreMesa = this.getTitle(); // Quedó configurado como "Mesa 1", "Mesa 2", etc.

            conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();

            // 3. Verificamos si ese producto ya estaba anotado en la libreta de esta mesa
            String sqlCheck = "SELECT cantidad FROM pedidos_temporales WHERE mesa = ? AND producto = ?";
            java.sql.PreparedStatement pstCheck = conexion.prepareStatement(sqlCheck);
            pstCheck.setString(1, nombreMesa);
            pstCheck.setString(2, productoSeleccionado);
            java.sql.ResultSet rs = pstCheck.executeQuery();

            if (rs.next()) {
                // Si ya estaba, sumamos la cantidad vieja con la nueva
                int cantidadActual = rs.getInt("cantidad");
                int cantidadTotal = cantidadActual + cantidadNueva;
                double nuevoSubtotal = precioUnitario * cantidadTotal;

                String sqlUpdate = "UPDATE pedidos_temporales SET cantidad = ?, subtotal = ? WHERE mesa = ? AND producto = ?";
                java.sql.PreparedStatement pstUpdate = conexion.prepareStatement(sqlUpdate);
                pstUpdate.setInt(1, cantidadTotal);
                pstUpdate.setDouble(2, nuevoSubtotal);
                pstUpdate.setString(3, nombreMesa);
                pstUpdate.setString(4, productoSeleccionado);
                pstUpdate.executeUpdate();
                pstUpdate.close();
            } else {
                // Si es un producto nuevo para esta mesa, lo anotamos por primera vez
                double subtotal = precioUnitario * cantidadNueva;
                String sqlInsert = "INSERT INTO pedidos_temporales (mesa, producto, precio, cantidad, subtotal) VALUES (?, ?, ?, ?, ?)";
                java.sql.PreparedStatement pstInsert = conexion.prepareStatement(sqlInsert);
                pstInsert.setString(1, nombreMesa);
                pstInsert.setString(2, productoSeleccionado);
                pstInsert.setDouble(3, precioUnitario);
                pstInsert.setInt(4, cantidadNueva);
                pstInsert.setDouble(5, subtotal);
                pstInsert.executeUpdate();
                pstInsert.close();
            }

            pstCheck.close();
            // Recuerda: NO hay conexion.close() aquí para cuidar a la cocina

            // 4. ¡MAGIA! Recargamos la tabla visual para que muestre lo que guardamos
            cargarPedidoMesa(nombreMesa);

            jTextField1.setText("");
            jTextField1.requestFocus();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar en la mesa: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // 1. Verificamos que hayas seleccionado un producto
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona un producto de la factura haciendo clic en la tabla.");
            return;
        }

        String cantidadTexto = jTextField1.getText(); 
        if (cantidadTexto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Escribe la nueva cantidad en la cajita de arriba y vuelve a presionar este botón.");
            return;
        }

        try {
            int nuevaCantidad = Integer.parseInt(cantidadTexto);
            if(nuevaCantidad <= 0) {
                 javax.swing.JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a cero. Si quieres quitar el producto, usa el botón 'Quitar Producto'.");
                 return;
            }

            // 2. Tomamos los datos de la fila seleccionada
            javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            String productoSeleccionado = modeloTabla.getValueAt(filaSeleccionada, 0).toString();
            double precioUnitario = Double.parseDouble(modeloTabla.getValueAt(filaSeleccionada, 1).toString());
            
            double nuevoSubtotal = precioUnitario * nuevaCantidad;
            String nombreMesa = this.getTitle();

            // 3. ✨ MAGIA: Actualizamos la libreta en la Base de Datos ✨
            conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();
            String sqlUpdate = "UPDATE pedidos_temporales SET cantidad = ?, subtotal = ? WHERE mesa = ? AND producto = ?";
            java.sql.PreparedStatement pstUpdate = conexion.prepareStatement(sqlUpdate);
            pstUpdate.setInt(1, nuevaCantidad);
            pstUpdate.setDouble(2, nuevoSubtotal);
            pstUpdate.setString(3, nombreMesa);
            pstUpdate.setString(4, productoSeleccionado);
            pstUpdate.executeUpdate();
            pstUpdate.close();
            // ¡Sin cerrar la conexión general para no pelear con la cocina!

            // 4. Recargamos la tabla visual para ver el cambio instantáneo
            cargarPedidoMesa(nombreMesa);

            // Limpiamos la cajita
            jTextField1.setText("");
            jTextField1.requestFocus();

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido.");
        } catch (Exception ex) {
            System.out.println("Error al actualizar la cantidad en BD: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona el producto que deseas quitar de la factura.");
            return;
        }

        // 1. Tomamos el nombre del producto que vamos a borrar
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        String productoSeleccionado = modeloTabla.getValueAt(filaSeleccionada, 0).toString();
        String nombreMesa = this.getTitle();

        try {
            // 2. ✨ MAGIA: Borramos ese producto específico de la libreta ✨
            conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();
            String sqlDelete = "DELETE FROM pedidos_temporales WHERE mesa = ? AND producto = ?";
            java.sql.PreparedStatement pstDelete = conexion.prepareStatement(sqlDelete);
            pstDelete.setString(1, nombreMesa);
            pstDelete.setString(2, productoSeleccionado);
            pstDelete.executeUpdate();
            pstDelete.close();

            // 3. Recargamos la tabla visual (y el total se recalcula solito)
            cargarPedidoMesa(nombreMesa);

        } catch (Exception ex) {
             System.out.println("Error al eliminar producto de la BD: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Verificamos que la factura no esté vacía
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        if (modeloTabla.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "La cuenta está vacía. Agrega productos antes de cobrar.");
            return;
        }

        try {
            // 2. Abrimos la puerta a la Base de Datos
            conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();
            
            // --- ✨ LA MAGIA DE LA SECUENCIA (1, 2, 3...) ✨ ---
            int idFacturaUnico = 1; // Empezamos en 1 por defecto
            try {
                java.sql.Statement stId = conexion.createStatement();
                java.sql.ResultSet rsId = stId.executeQuery("SELECT MAX(id_factura) FROM ventas");
                if (rsId.next()) {
                    int ultimoId = rsId.getInt(1);
                    if (ultimoId > 0) {
                        idFacturaUnico = ultimoId + 1; // Tomamos el último número y le sumamos 1
                    }
                }
            } catch (Exception e) {
                System.out.println("Error al buscar el último ID: " + e.getMessage());
            }

            // 3. Recorremos toda la factura para descontar los productos del inventario
            for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                String nombreProducto = modeloTabla.getValueAt(i, 0).toString(); // Columna 0: Nombre
                int cantidadVendida = Integer.parseInt(modeloTabla.getValueAt(i, 2).toString()); // Columna 2: Cantidad

                // Le decimos a MySQL: "A la cantidad que tienes, réstale la cantidad que acabo de vender"
                String sql = "UPDATE productos SET cantidad = cantidad - ? WHERE nombre = ?";
                java.sql.PreparedStatement pst = conexion.prepareStatement(sql);
                
                pst.setInt(1, cantidadVendida);
                pst.setString(2, nombreProducto);
                
                pst.executeUpdate(); // Disparamos la orden
                
                // ... (Tú ya tienes el for y la parte del UPDATE de inventario aquí arriba) ...

                    // --- AQUÍ EMPIEZA LO NUEVO PARA LA TABLA VENTAS ---
                    String sqlVenta = "INSERT INTO ventas (id_factura, producto, cantidad, subtotal, fecha) VALUES (?, ?, ?, ?, NOW())"; 
                    java.sql.PreparedStatement pstVenta = conexion.prepareStatement(sqlVenta);

                    // Sacamos el subtotal que está en la columna 3 de la fila actual de la tabla
                    double subtotalFila = Double.parseDouble(modeloTabla.getValueAt(i, 3).toString());

                    pstVenta.setInt(1, idFacturaUnico); // 1. El ID de la factura
                    pstVenta.setString(2, nombreProducto); // 2. El nombre
                    pstVenta.setInt(3, cantidadVendida);   // 3. La cantidad
                    pstVenta.setDouble(4, subtotalFila);    // 4. El subtotal

                    pstVenta.executeUpdate(); 
                    pstVenta.close();        // Cerramos esta instrucción
                    
                                 
                pst.close(); // Cerramos la instrucción
            }
            
            //conexion.close(); // Cerramos la puerta de la base de datos
            
            // ---   ENVIAR COMANDA A COCINA ---
            try {
                // 1. Recopilamos todo lo que pidió el cliente en un solo texto gigante
                String detallePedido = "";
                for (int j = 0; j < modeloTabla.getRowCount(); j++) {
                    String cant = modeloTabla.getValueAt(j, 2).toString();
                    String prod = modeloTabla.getValueAt(j, 0).toString();
                    detallePedido += cant + "x " + prod + "\n"; // Quedará como "2x Café"
                }

                // 2. Averiguamos de dónde viene el pedido
                String origenPedido = "Caja Principal"; // Por defecto, si compran de pie
                if (botonMesaActual != null) {
                    origenPedido = this.getTitle(); // Toma el nombre de la ventana (Ej: "Factura de: Mesa 1")
                }

                // 3. Lo inyectamos en la nueva base de datos de la cocina
                String sqlComanda = "INSERT INTO comandas (mesa, detalle, estado) VALUES (?, ?, 'PENDIENTE')";
                java.sql.PreparedStatement pstComanda = conexion.prepareStatement(sqlComanda);
                pstComanda.setString(1, origenPedido);
                pstComanda.setString(2, detallePedido);
                pstComanda.executeUpdate();
                pstComanda.close();
                
            } catch (Exception e) {
                System.out.println("Error al enviar comanda a la cocina: " + e.getMessage());
            }
            // --- FIN DE LA COMANDA ---

            // 4. ¡Celebramos el éxito!
            javax.swing.JOptionPane.showMessageDialog(this, "¡Venta registrada con éxito! El inventario de Mi Raquelita ha sido actualizado.");
            
            // --- INICIO CÓDIGO DEL TICKET EN PDF ---
            try {
                // 1. Creamos el documento PDF
                com.itextpdf.text.Document documento = new com.itextpdf.text.Document();
                String nombreArchivo = "Ticket_" + idFacturaUnico + ".pdf";
                com.itextpdf.text.pdf.PdfWriter.getInstance(documento, new java.io.FileOutputStream(nombreArchivo));

                documento.open();

                // 2. Dibujamos el encabezado del ticket
                documento.add(new com.itextpdf.text.Paragraph("========================================"));
                documento.add(new com.itextpdf.text.Paragraph("            MI RAQUELITA CAFÉ           "));
                documento.add(new com.itextpdf.text.Paragraph("========================================"));
                documento.add(new com.itextpdf.text.Paragraph("Factura #: " + idFacturaUnico));
                documento.add(new com.itextpdf.text.Paragraph("Fecha: " + new java.util.Date().toString()));
                documento.add(new com.itextpdf.text.Paragraph("----------------------------------------"));
                documento.add(new com.itextpdf.text.Paragraph("CANT  PRODUCTO                SUBTOTAL"));
                documento.add(new com.itextpdf.text.Paragraph("----------------------------------------"));

                double totalTicket = 0;
                
                // 3. Recorremos la tabla para anotar lo que compró
                for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                    String prod = modeloTabla.getValueAt(i, 0).toString();
                    String cant = modeloTabla.getValueAt(i, 2).toString();
                    String sub = modeloTabla.getValueAt(i, 3).toString();
                    
                    totalTicket += Double.parseDouble(sub);

                    documento.add(new com.itextpdf.text.Paragraph(cant + " x " + prod + "  ->  $ " + sub));
                }

                // 4. Pie de página y totales
                documento.add(new com.itextpdf.text.Paragraph("----------------------------------------"));
                documento.add(new com.itextpdf.text.Paragraph("TOTAL A PAGAR:          $ " + totalTicket));
                documento.add(new com.itextpdf.text.Paragraph("========================================"));
                documento.add(new com.itextpdf.text.Paragraph("       ¡Gracias por su compra!          "));
                documento.add(new com.itextpdf.text.Paragraph("========================================"));

                // 5. Cerramos el "dibujo" del PDF
                documento.close(); 
                
                // 6. ¡MAGIA! Le decimos a Windows que abra el PDF automáticamente
                java.awt.Desktop.getDesktop().open(new java.io.File(nombreArchivo));
                
            } catch (Exception e) {
                System.out.println("Error al crear el ticket PDF: " + e.getMessage());
            }
            // --- FIN CÓDIGO DEL TICKET EN PDF ---

            // 5. Limpiamos la pantalla para el siguiente cliente
            modeloTabla.setRowCount(0); // Borra todas las filas de la tabla
            jLabel1.setText("TOTAL: $ 0"); // Pone el total en cero (¡Cámbiale el número si tu total no es jLabel1!)
            
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al procesar la venta: " + e.toString());
        }
        
        // --- NUEVO: LIBERAR LA MESA ---
         if (botonMesaActual != null) {
             botonMesaActual.setBackground(java.awt.Color.GREEN); // La volvemos a poner Libre

             // --- ✨ MAGIA: BORRAMOS LA MEMORIA DE LA BASE DE DATOS AL COBRAR ✨ ---
             try {
                 conexion.ConexionDB con2 = new conexion.ConexionDB();
                 java.sql.Connection conexion2 = con2.establecerConexion();
                 String sqlLimpiar = "DELETE FROM pedidos_temporales WHERE mesa = ?";
                 java.sql.PreparedStatement pstLimpiar = conexion2.prepareStatement(sqlLimpiar);
                 pstLimpiar.setString(1, this.getTitle());
                 pstLimpiar.executeUpdate();
                 pstLimpiar.close();
             } catch (Exception exLimpiar) {
                 System.out.println("Error al limpiar memoria de la mesa: " + exLimpiar.getMessage());
             }

             this.dispose(); // Cerramos la ventana de ventas para volver al mapa
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // 1. Cerramos la ventana de la factura actual
        this.dispose();

        // 2. ¿Veníamos de atender una mesa?
        if (this.botonMesaActual != null) {
            // Si SÍ veníamos de una mesa, buscamos la Pantalla de Mesas y la traemos al frente
            for (java.awt.Window ventana : java.awt.Window.getWindows()) {
                if (ventana instanceof PantallaMesas) {
                    ventana.setVisible(true);
                    ventana.toFront();
                    break;
                }
            }
        } else {
            // Si NO veníamos de una mesa (entramos por otro lado), buscamos el Menú Principal
            boolean menuEncontrado = false;
            for (java.awt.Window ventana : java.awt.Window.getWindows()) {
                if (ventana instanceof PantallaPrincipa) {
                    ventana.setVisible(true);
                    ventana.toFront();
                    menuEncontrado = true;
                    break;
                }
            }
            // Si por algún motivo el menú estaba cerrado, creamos uno nuevo
            if (!menuEncontrado) {
                new PantallaPrincipa().setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // --- ENVIAR COMANDA A COCINA Y ABRIR TICKET ---
        try {
            javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            if (modeloTabla.getRowCount() == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay productos para enviar a la cocina.");
                return;
            }

            // 1. Recopilamos todo lo que pidió el cliente
            String detallePedido = "";
            for (int j = 0; j < modeloTabla.getRowCount(); j++) {
                String cant = modeloTabla.getValueAt(j, 2).toString();
                String prod = modeloTabla.getValueAt(j, 0).toString();
                detallePedido += cant + "x " + prod + "\n"; 
            }

            // 2. Averiguamos de dónde viene el pedido
            String origenPedido = "Caja Principal"; 
            if (botonMesaActual != null) {
                origenPedido = this.getTitle(); 
            }

            // 3. Lo inyectamos en la base de datos de la cocina y RECUPERAMOS SU ID
            conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();
            
            String sqlComanda = "INSERT INTO comandas (mesa, detalle, estado) VALUES (?, ?, 'PENDIENTE')";
            // ✨ Cambio aquí: Le pedimos a MySQL que nos devuelva el ID
            java.sql.PreparedStatement pstComanda = conexion.prepareStatement(sqlComanda, java.sql.Statement.RETURN_GENERATED_KEYS);
            pstComanda.setString(1, origenPedido);
            pstComanda.setString(2, detallePedido);
            pstComanda.executeUpdate();
            
            // Sacamos el ID secreto que le asignó la base de datos
            int idGenerado = 0;
            java.sql.ResultSet rsComanda = pstComanda.getGeneratedKeys();
            if(rsComanda.next()){ idGenerado = rsComanda.getInt(1); }
            
            pstComanda.close();
            

            // 4. ---  CONSECUTIVO (1, 2, 3...) ---
            int ticketsAbiertos = 1;
            for (java.awt.Window ventana : java.awt.Window.getWindows()) {
                // Cuenta cuántos tickets flotantes hay vivos en la pantalla
                if (ventana instanceof PantallaComandas && ventana.isVisible()) {
                    ticketsAbiertos++;
                }
            }
            
            // 5. ¡LANZAMOS EL TICKET A LA PANTALLA DE LA COCINA!
            PantallaComandas ticket = new PantallaComandas(idGenerado, origenPedido, detallePedido, ticketsAbiertos);
            ticket.setVisible(true);
            
            javax.swing.JOptionPane.showMessageDialog(this, "¡Pedido volando a la cocina!");
            
        } catch (Exception e) {
            System.out.println("Error al enviar comanda: " + e.getMessage());
        }
        // --- FIN DE LA COMANDA ---
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaVentas().setVisible(true));
    }
    
    // --- MÉTODO PARA CARGAR LA MEMORIA DE LA MESA ---
    public void cargarPedidoMesa(String nombreMesa) {
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modeloTabla.setRowCount(0); // Borramos lo visual para traer lo fresco de la base de datos
        double totalFactura = 0;

        try {
            conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();
            
            // Buscamos solo los productos de la mesa que estamos abriendo
            String sql = "SELECT producto, precio, cantidad, subtotal FROM pedidos_temporales WHERE mesa = ?";
            java.sql.PreparedStatement pst = conexion.prepareStatement(sql);
            pst.setString(1, nombreMesa);
            java.sql.ResultSet rs = pst.executeQuery();

            // Llenamos la tablita con lo que encontró
            while (rs.next()) {
                String prod = rs.getString("producto");
                double precio = rs.getDouble("precio");
                int cant = rs.getInt("cantidad");
                double sub = rs.getDouble("subtotal");
                
                modeloTabla.addRow(new Object[]{prod, precio, cant, sub});
                totalFactura += sub;
            }
            
            jLabel1.setText("TOTAL: $ " + totalFactura);
            pst.close();
            // Recuerda: ¡No ponemos conexion.close() para evitar el error rojo de la cocina!
            
        } catch (Exception e) {
            System.out.println("Error al cargar la memoria de la mesa: " + e.getMessage());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
