/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Administrador
 */
public class PantallaPrincipa extends javax.swing.JFrame {
    public double baseCaja = 0; // Aquí guardaremos la plata del inicio del día
    public int idTurnoActual = 0;
    public String horaAperturaTurno = "";
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipa.class.getName());

    /**
     * Creates new form PantallaPrincipa
     */
    public PantallaPrincipa() {
        initComponents();
        cargarGraficoVentas();  // Aquí me carga la grafica
        cargarGraficoPastel();  // Aquí me carga la grafica de pastel
        comprobarEstadoCaja();  // Aquí comprueba la base de datos
        
        // ✨ AQUÍ DEBE IR EL TRUCO PARA ACTUALIZAR AL VOLVER ✨
        this.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            @Override
            public void windowGainedFocus(java.awt.event.WindowEvent e) {
                // El vigilante solo actualizará las gráficas
                cargarGraficoVentas();
                cargarGraficoPastel();
                
            }

            @Override
            public void windowLostFocus(java.awt.event.WindowEvent e) {}
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAbrirCaja = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sistema POS - Mi Raquelita");

        jButton1.setText("Gestión de Mesas");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Inventario");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Caja / Ventas");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        btnAbrirCaja.setText("Abrir Caja");
        btnAbrirCaja.addActionListener(this::btnAbrirCajaActionPerformed);

        jButton5.setText("Cerrar Turno");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(btnAbrirCaja)
                    .addComponent(jButton5))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(btnAbrirCaja)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 1. Creamos la nueva ventana en la memoria
        PantallaInventario ventanaInv = new PantallaInventario();

        // 2. Le decimos que se haga visible
        ventanaInv.setVisible(true);

        // 3. Cerramos la ventana actual (el menú) para no acumular ventanas abiertas
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PantallaMesas ventanaMesas = new PantallaMesas();
        ventanaMesas.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PantallaReportes ventanaReportes = new PantallaReportes();
        ventanaReportes.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnAbrirCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirCajaActionPerformed
            try {
        // 1. Pedimos el nombre del cajero
            String nombreCajero = javax.swing.JOptionPane.showInputDialog(this, "Nombre del cajero responsable:");
            if (nombreCajero == null || nombreCajero.trim().isEmpty()) return;

            // 2. Pedimos el monto inicial
            String montoInput = javax.swing.JOptionPane.showInputDialog(this, "Efectivo inicial para el turno de " + nombreCajero + ":");
            if (montoInput == null || montoInput.isEmpty()) return;

            baseCaja = Double.parseDouble(montoInput);

            // 3. Guardamos en la Base de Datos
            conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();
            
            String sql = "INSERT INTO caja_diaria (base_inicial, fecha_apertura, estado, cajero) VALUES (?, NOW(), 'ABIERTA', ?)";
            java.sql.PreparedStatement pst = conexion.prepareStatement(sql, java.sql.Statement.RETURN_GENERATED_KEYS);
            pst.setDouble(1, baseCaja);
            pst.setString(2, nombreCajero);
            pst.executeUpdate();

            java.sql.ResultSet rs = pst.getGeneratedKeys();
            if (rs.next()) { idTurnoActual = rs.getInt(1); }
            
            conexion.close();
            comprobarEstadoCaja(); 
            javax.swing.JOptionPane.showMessageDialog(this, "¡Turno iniciado por " + nombreCajero + "!");
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAbrirCajaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            try {
        conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();
            
            // 1. Buscamos ventas SOLO en el rango de este turno
            String sqlVentas = "SELECT SUM(subtotal) AS total FROM ventas WHERE fecha >= CAST(? AS DATETIME)";
            java.sql.PreparedStatement pstVentas = conexion.prepareStatement(sqlVentas);
            pstVentas.setString(1, horaAperturaTurno);
            java.sql.ResultSet rsV = pstVentas.executeQuery();
            
            double totalVentasTurno = 0;
            if (rsV.next()) { totalVentasTurno = rsV.getDouble("total"); }

            double granTotalCaja = baseCaja + totalVentasTurno;
            
            // ---  Buscamos el nombre de quién abrió este turno ---
            String responsable = "No asignado";
            try {
                java.sql.PreparedStatement pstNombre = conexion.prepareStatement("SELECT cajero FROM caja_diaria WHERE id = ?");
                pstNombre.setInt(1, idTurnoActual);
                java.sql.ResultSet rsN = pstNombre.executeQuery();
                if (rsN.next()) {
                    responsable = rsN.getString("cajero");
                }
            } catch (Exception e) {
                System.out.println("Error al buscar nombre: " + e.getMessage());
            }

            String mensaje = "RESUMEN DE ESTE TURNO\n"
                           + "Inicio: " + horaAperturaTurno + "\n"
                           + "Base: $ " + baseCaja + "\n"
                           + "Ventas: $ " + totalVentasTurno + "\n"
                           + "EFECTIVO EN CAJA: $ " + granTotalCaja;

            int opc = javax.swing.JOptionPane.showConfirmDialog(this, mensaje + "\n\n¿Cerrar turno definitivamente e imprimir ticket?", "Cierre de Turno", javax.swing.JOptionPane.YES_NO_OPTION);

            if (opc == javax.swing.JOptionPane.YES_OPTION) {
                // 2. ACTUALIZAMOS LA BASE DE DATOS (Cerramos la caja oficialmente)
                String sqlCierre = "UPDATE caja_diaria SET fecha_cierre = NOW(), estado = 'CERRADA' WHERE id = ?";
                java.sql.PreparedStatement pstC = conexion.prepareStatement(sqlCierre);
                pstC.setInt(1, idTurnoActual);
                pstC.executeUpdate();

                // ---  MAGIA: GENERAMOS EL PDF DEL CIERRE  ---
                try {
                    com.itextpdf.text.Document documento = new com.itextpdf.text.Document();
                    String nombreArchivo = "Cierre_Turno_" + idTurnoActual + ".pdf";
                    com.itextpdf.text.pdf.PdfWriter.getInstance(documento, new java.io.FileOutputStream(nombreArchivo));

                    documento.open();
                    documento.add(new com.itextpdf.text.Paragraph("========================================"));
                    documento.add(new com.itextpdf.text.Paragraph("          CIERRE DE CAJA - MI RAQUELITA         "));
                    documento.add(new com.itextpdf.text.Paragraph("========================================"));
                    documento.add(new com.itextpdf.text.Paragraph("Turno #: " + idTurnoActual));                    
                    documento.add(new com.itextpdf.text.Paragraph("Responsable:      " + responsable));
                    documento.add(new com.itextpdf.text.Paragraph("Apertura: " + horaAperturaTurno));
                    documento.add(new com.itextpdf.text.Paragraph("Cierre: " + new java.util.Date().toString()));
                    documento.add(new com.itextpdf.text.Paragraph("----------------------------------------"));
                    documento.add(new com.itextpdf.text.Paragraph("Base Inicial:        $ " + baseCaja));
                    documento.add(new com.itextpdf.text.Paragraph("Total Ventas:        $ " + totalVentasTurno));
                    documento.add(new com.itextpdf.text.Paragraph("----------------------------------------"));
                    documento.add(new com.itextpdf.text.Paragraph("TOTAL EN CAJA:       $ " + granTotalCaja));
                    documento.add(new com.itextpdf.text.Paragraph("========================================"));
                    documento.close();

                    // Abrimos el PDF automático
                    java.awt.Desktop.getDesktop().open(new java.io.File(nombreArchivo));
                } catch (Exception pdfEx) {
                    System.out.println("Error al crear PDF de Cierre: " + pdfEx.getMessage());
                }
                // --- FIN DEL PDF ---

                javax.swing.JOptionPane.showMessageDialog(this, "Turno cerrado exitosamente. El reporte ha sido generado.");
                
                // 3. Reiniciamos la seguridad de la pantalla
                baseCaja = 0;
                idTurnoActual = 0;
                horaAperturaTurno = "";
                
                btnAbrirCaja.setEnabled(true);   // Dejamos listo para el nuevo cajero
                jButton5.setEnabled(false);      // Apagamos botón cerrar
                jButton1.setEnabled(false);      // Bloqueamos mesas por seguridad
            }
            conexion.close();
        } catch (Exception e) {
            System.out.println("Error en Cierre Pro: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipa().setVisible(true));
    }
    
    public void cargarGraficoVentas() {
    // 1. Creamos el contenedor de los datos
    org.jfree.data.category.DefaultCategoryDataset dataset = new org.jfree.data.category.DefaultCategoryDataset();

    try {
        // 2. Nos conectamos a la base de datos
        conexion.ConexionDB con = new conexion.ConexionDB();
        java.sql.Connection conexion = con.establecerConexion();
        java.sql.Statement st = conexion.createStatement();
        
        // 3. Consulta: Sumamos las cantidades vendidas por cada producto y sacamos los 5 mejores
        String sql = "SELECT producto, SUM(cantidad) as total_vendido FROM ventas GROUP BY producto ORDER BY total_vendido DESC LIMIT 5";
        java.sql.ResultSet rs = st.executeQuery(sql);

        // 4. Metemos los datos de MySQL al contenedor de la gráfica
        while (rs.next()) {
            String nombreProducto = rs.getString("producto");
            String nombreFormateado = nombreProducto.replace(" ", "\n");
            int cantidad = rs.getInt("total_vendido");
            dataset.addValue(cantidad, "Ventas", nombreFormateado);
        }
        conexion.close();
    } catch (Exception e) {
        System.out.println("Error al cargar datos para la gráfica: " + e.getMessage());
    }

    // 5. Dibujamos la gráfica de barras
    org.jfree.chart.JFreeChart grafica = org.jfree.chart.ChartFactory.createBarChart(
        "Top 5 Productos Más Vendidos", // Título de la gráfica
        "Productos",                    // Etiqueta del Eje X (Abajo)
        "Unidades Vendidas",            // Etiqueta del Eje Y (Lado)
        dataset,
        org.jfree.chart.plot.PlotOrientation.VERTICAL,
        false, true, false
    );
    
    org.jfree.chart.plot.CategoryPlot plot = grafica.getCategoryPlot();
    org.jfree.chart.axis.CategoryAxis ejeX = plot.getDomainAxis();
    ejeX.setCategoryLabelPositions(org.jfree.chart.axis.CategoryLabelPositions.UP_45);
    ejeX.setMaximumCategoryLabelLines(3);
    org.jfree.chart.axis.NumberAxis ejeY = (org.jfree.chart.axis.NumberAxis) plot.getRangeAxis();
    ejeY.setStandardTickUnits(org.jfree.chart.axis.NumberAxis.createIntegerTickUnits());
    
    // 1. Definimos una paleta de colores professional para cafetería
    java.awt.Color[] colores = {
        new java.awt.Color(139, 69, 19),  // ☕ Café Oscuro
        new java.awt.Color(205, 133, 63), // 🥐 Café con Leche / Dorado Pastelería
        new java.awt.Color(255, 165, 0),   // 🍊 Naranja Brillante (Jugos/Aguapanela)
        new java.awt.Color(255, 215, 0),   // ✨ Oro (Toque premium/Empanadas)
        new java.awt.Color(107, 142, 35)   // 🍵 Verde Oliva (Un toque distintivo y natural)
    };

    // 2. Creamos un renderizador de barras personalizado para asignar colores por ítem
    org.jfree.chart.renderer.category.BarRenderer renderer = new org.jfree.chart.renderer.category.BarRenderer() {
        @Override
        public java.awt.Paint getItemPaint(int row, int column) {
            // Asigna un color diferente a cada barra (columna) basándose en nuestra paleta
            // Usamos el operador % por si vendiéramos más de 5, para que los colores se repitan
            return colores[column % colores.length];
        }
    };

    // 3. Un toque final: Quitar los bordes negros de las barras para que se vean más limpias
    renderer.setDrawBarOutline(false);
    
    // 4. Aplicamos el nuevo renderizador colorido a la gráfica
    plot.setRenderer(renderer);
    

    // 6. Convertimos la gráfica en un Panel visual
    org.jfree.chart.ChartPanel panelGrafica = new org.jfree.chart.ChartPanel(grafica);
    // Le decimos que tome el tamaño exacto de tu jPanel1
    panelGrafica.setPreferredSize(new java.awt.Dimension(jPanel1.getWidth(), jPanel1.getHeight()));

    // 7. Acomodamos tu jPanel1 y le pegamos la gráfica adentro
    jPanel1.setLayout(new java.awt.BorderLayout());
    jPanel1.removeAll(); // Limpiamos por si había algo antes
    jPanel1.add(panelGrafica, java.awt.BorderLayout.CENTER);
    jPanel1.validate(); // Refrescamos la pantalla para que se vea
}
    
    public void cargarGraficoPastel() {
    // 1. Creamos el contenedor de datos circular
    org.jfree.data.general.DefaultPieDataset dataset = new org.jfree.data.general.DefaultPieDataset();

    try {
        // 2. Nos conectamos a la base de datos
        conexion.ConexionDB con = new conexion.ConexionDB();
        java.sql.Connection conexion = con.establecerConexion();
        java.sql.Statement st = conexion.createStatement();
        
        // 3. Consulta: Ahora no sumamos "cantidad", sino "subtotal" (el dinero)
        String sql = "SELECT producto, SUM(subtotal) as ingresos FROM ventas GROUP BY producto ORDER BY ingresos DESC LIMIT 5";
        java.sql.ResultSet rs = st.executeQuery(sql);

        // 4. Llenamos el pastel con los datos de ganancias
        while (rs.next()) {
            String nombreProducto = rs.getString("producto");
            String nombreFormateado = nombreProducto.replace(" ", "\n");
            double ingresos = rs.getDouble("ingresos");
            // Aquí le pasamos el nombre y la platica que generó
            dataset.setValue(nombreFormateado, ingresos); 
        }
        conexion.close();
    } catch (Exception e) {
        System.out.println("Error al cargar datos para el pastel: " + e.getMessage());
    }

    // 5. Dibujamos el gráfico de pastel
    org.jfree.chart.JFreeChart graficaPastel = org.jfree.chart.ChartFactory.createPieChart(
        "Top 5 Productos por Ingresos ($)", // Título
        dataset,                            // Los datos
        true,                               // Mostrar cuadro de colores (Leyenda)
        true,                               // Mostrar etiquetas al pasar el mouse
        false
    );

    // --- Toques de estética para que se vea moderno ---
    org.jfree.chart.plot.PiePlot plot = (org.jfree.chart.plot.PiePlot) graficaPastel.getPlot();
    plot.setLabelGenerator(null);
    plot.setBackgroundPaint(java.awt.Color.WHITE); // Fondo blanco limpio
    plot.setOutlineVisible(false); // Quitar el borde negro exterior
    // --------------------------------------------------

    // 6. Convertimos el gráfico en un Panel visual
    org.jfree.chart.ChartPanel panelGrafica = new org.jfree.chart.ChartPanel(graficaPastel);
    panelGrafica.setPreferredSize(new java.awt.Dimension(jPanel2.getWidth(), jPanel2.getHeight()));

    // 7. Lo agregamos a tu nuevo jPanel2
    jPanel2.setLayout(new java.awt.BorderLayout());
    jPanel2.removeAll(); 
    jPanel2.add(panelGrafica, java.awt.BorderLayout.CENTER);
    jPanel2.validate(); 
}

public void comprobarEstadoCaja() {
    try {
        conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();
            java.sql.Statement st = conexion.createStatement();

            // ---  1. ESTADO POR DEFECTO (Caja Cerrada)  ---
            // Asumimos que no hay turno. Apagamos ventas y encendemos apertura.
            btnAbrirCaja.setEnabled(true);   // Puedes abrir caja
            jButton1.setEnabled(false);      // NO puedes gestionar mesas
            jButton5.setEnabled(false);      // NO puedes cerrar un turno inexistente

            // 2. Buscamos si en la base de datos hay una caja ABIERTA
            String sql = "SELECT *, DATE(fecha_apertura) as solo_fecha FROM caja_diaria WHERE estado = 'ABIERTA' ORDER BY id DESC LIMIT 1";
            java.sql.ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                // ---  3. SI HAY CAJA ABIERTA, CAMBIAMOS LAS REGLAS  ---
                btnAbrirCaja.setEnabled(false); // Ya está abierta, no puedes abrir otra
                jButton5.setEnabled(true);      // Se habilita el botón de Cerrar Turno

                String fechaCajaTexto = rs.getString("solo_fecha");
                String fechaHoyTexto = new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());

                if (!fechaCajaTexto.equals(fechaHoyTexto)) {
                    // CASO A: Es de un día anterior (Bloqueamos mesas por seguridad)
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "¡ATENCIÓN SEGURIDAD!\nHay una caja abierta del día anterior: " + fechaCajaTexto 
                        + "\nDebes cerrar ese turno antes de poder trabajar hoy.", 
                        "Cierre Pendiente Detectado", javax.swing.JOptionPane.WARNING_MESSAGE);
                    
                    jButton1.setEnabled(false); // Mesas siguen bloqueadas
                } else {
                    // CASO B: Es de hoy. ¡Todo en orden, a vender!
                    jButton1.setEnabled(true); // ¡SE HABILITAN LAS MESAS!
                    
                    // Guardamos los datos en la memoria
                    idTurnoActual = rs.getInt("id");
                    baseCaja = rs.getDouble("base_inicial");
                    horaAperturaTurno = rs.getString("fecha_apertura");
                }
            }
            conexion.close();
            
        } catch (Exception e) {
            System.out.println("Error en Auditoría Pro: " + e.getMessage());
        }
}

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirCaja;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
