/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorInventario;
import modelo.Producto;
import java.util.ArrayList;

/**
 *
 * @author Administrador
 */
public class PantallaVentas extends javax.swing.JFrame {
    
    javax.swing.JButton botonMesaActual; // Recordará qué mesa estamos atendiendo
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaVentas.class.getName());

    /**
     * Creates new form PantallaVentas
     */
    public PantallaVentas() {
        initComponents();
        cargarProductosEnCombo();
    }
    
    public void configurarMesa(javax.swing.JButton botonMesa, String nombreMesa) {
     this.botonMesaActual = botonMesa;
        this.setTitle(nombreMesa); // Le dejamos solo el nombre limpio (Ej: "Mesa 1")
        this.botonMesaActual.setBackground(java.awt.Color.RED); 
        
        // Se llama al lector al abrir ventana
        cargarPedidoMesa(nombreMesa);
 }
    
    private void cargarProductosEnCombo() {
        jComboBox1.removeAllItems(); // Borramos los ítems por defecto
        
        ControladorInventario control = new ControladorInventario();
        ArrayList<Producto> lista = control.obtenerTodosLosProductos(); // Traemos los datos de DDBB
        
        for (Producto p : lista) {
            jComboBox1.addItem(p.getNombre()); // Metemos los nombres al desplegable
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio Unitario", "Cantidad", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("TOTAL: $ 0");

        jButton1.setText("COBRAR  / FACTURAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel2.setText("Producto");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Cantidad");

        jButton2.setText("Agregar a la cuenta");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Cambiar Cantidad");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Quitar Producto");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton9.setText("Volver a Mesas");
        jButton9.addActionListener(this::jButton9ActionPerformed);

        jButton5.setText("ENVIAR A COCINA");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(120, 120, 120)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(0, 650, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton9))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String productoSeleccionado = jComboBox1.getSelectedItem().toString();
        String cantidadTexto = jTextField1.getText();

        if (cantidadTexto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, escribe una cantidad.");
            return; 
        }

        try {
            int cantidadNueva = Integer.parseInt(cantidadTexto); 

            // Obtenemos el precio del producto consultando el inventario
            controlador.ControladorInventario control = new controlador.ControladorInventario();
            java.util.ArrayList<modelo.Producto> lista = control.obtenerTodosLosProductos();
            double precioUnitario = 0;
            for (modelo.Producto p : lista) {
                if (p.getNombre().equals(productoSeleccionado)) {
                    precioUnitario = p.getPrecio();
                    break; 
                }
            }

            // El título de la ventana contiene el nombre de la mesa (ej: "Mesa 1")
            String nombreMesa = this.getTitle();

            conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();

            // Verificamos si este producto ya existe en el pedido de esta mesa
            String sqlCheck = "SELECT cantidad FROM pedidos_temporales WHERE mesa = ? AND producto = ?";
            java.sql.PreparedStatement pstCheck = conexion.prepareStatement(sqlCheck);
            pstCheck.setString(1, nombreMesa);
            pstCheck.setString(2, productoSeleccionado);
            java.sql.ResultSet rs = pstCheck.executeQuery();

            if (rs.next()) {
                // El producto ya estaba en el pedido: acumulamos la cantidad
                int cantidadActual = rs.getInt("cantidad");
                int cantidadTotal = cantidadActual + cantidadNueva;
                double nuevoSubtotal = precioUnitario * cantidadTotal;

                String sqlUpdate = "UPDATE pedidos_temporales SET cantidad = ?, subtotal = ? WHERE mesa = ? AND producto = ?";
                java.sql.PreparedStatement pstUpdate = conexion.prepareStatement(sqlUpdate);
                pstUpdate.setInt(1, cantidadTotal);
                pstUpdate.setDouble(2, nuevoSubtotal);
                pstUpdate.setString(3, nombreMesa);
                pstUpdate.setString(4, productoSeleccionado);
                pstUpdate.executeUpdate();
                pstUpdate.close();
            } else {
                // Producto nuevo en esta mesa: lo insertamos por primera vez
                double subtotal = precioUnitario * cantidadNueva;
                String sqlInsert = "INSERT INTO pedidos_temporales (mesa, producto, precio, cantidad, subtotal) VALUES (?, ?, ?, ?, ?)";
                java.sql.PreparedStatement pstInsert = conexion.prepareStatement(sqlInsert);
                pstInsert.setString(1, nombreMesa);
                pstInsert.setString(2, productoSeleccionado);
                pstInsert.setDouble(3, precioUnitario);
                pstInsert.setInt(4, cantidadNueva);
                pstInsert.setDouble(5, subtotal);
                pstInsert.executeUpdate();
                pstInsert.close();
            }

            pstCheck.close();

            // Refrescamos la tabla para reflejar el estado actual del pedido
            cargarPedidoMesa(nombreMesa);

            jTextField1.setText("");
            jTextField1.requestFocus();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar en la mesa: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Validamos que haya una fila seleccionada en la tabla
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona un producto de la factura haciendo clic en la tabla.");
            return;
        }

        String cantidadTexto = jTextField1.getText(); 
        if (cantidadTexto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Escribe la nueva cantidad en la cajita de arriba y vuelve a presionar este botón.");
            return;
        }

        try {
            int nuevaCantidad = Integer.parseInt(cantidadTexto);
            if(nuevaCantidad <= 0) {
                 javax.swing.JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a cero. Si quieres quitar el producto, usa el botón 'Quitar Producto'.");
                 return;
            }

            // Leemos el producto y precio desde la fila seleccionada en la tabla
            javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            String productoSeleccionado = modeloTabla.getValueAt(filaSeleccionada, 0).toString();
            double precioUnitario = Double.parseDouble(modeloTabla.getValueAt(filaSeleccionada, 1).toString());
            
            double nuevoSubtotal = precioUnitario * nuevaCantidad;
            String nombreMesa = this.getTitle();

            // Actualizamos la cantidad y subtotal en la base de datos
            conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();
            String sqlUpdate = "UPDATE pedidos_temporales SET cantidad = ?, subtotal = ? WHERE mesa = ? AND producto = ?";
            java.sql.PreparedStatement pstUpdate = conexion.prepareStatement(sqlUpdate);
            pstUpdate.setInt(1, nuevaCantidad);
            pstUpdate.setDouble(2, nuevoSubtotal);
            pstUpdate.setString(3, nombreMesa);
            pstUpdate.setString(4, productoSeleccionado);
            pstUpdate.executeUpdate();
            pstUpdate.close();


            // Recargamos la tabla para mostrar el cambio
            cargarPedidoMesa(nombreMesa);

            jTextField1.setText("");
            jTextField1.requestFocus();

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido.");
        } catch (Exception ex) {
            System.out.println("Error al actualizar la cantidad en BD: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona el producto que deseas quitar de la factura.");
            return;
        }

        // Obtenemos el nombre del producto a eliminar desde la tabla
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        String productoSeleccionado = modeloTabla.getValueAt(filaSeleccionada, 0).toString();
        String nombreMesa = this.getTitle();

        try {
            // Eliminamos el producto del pedido temporal de esta mesa
            conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();
            String sqlDelete = "DELETE FROM pedidos_temporales WHERE mesa = ? AND producto = ?";
            java.sql.PreparedStatement pstDelete = conexion.prepareStatement(sqlDelete);
            pstDelete.setString(1, nombreMesa);
            pstDelete.setString(2, productoSeleccionado);
            pstDelete.executeUpdate();
            pstDelete.close();

            // El total se recalcula automáticamente al recargar
            cargarPedidoMesa(nombreMesa);

        } catch (Exception ex) {
             System.out.println("Error al eliminar producto de la BD: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        // No procesamos si la factura está vacía
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        if (modeloTabla.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "La cuenta está vacía. Agrega productos antes de cobrar.");
            return;
        }

        try {
            
            conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();
            
            // Generamos el ID de factura tomando el máximo actual y sumando 1
            int idFacturaUnico = 1;
            try {
                java.sql.Statement stId = conexion.createStatement();
                java.sql.ResultSet rsId = stId.executeQuery("SELECT MAX(id_factura) FROM ventas");
                if (rsId.next()) {
                    int ultimoId = rsId.getInt(1);
                    if (ultimoId > 0) {
                        idFacturaUnico = ultimoId + 1; // Tomamos el último número y le sumamos 1
                    }
                }
            } catch (Exception e) {
                System.out.println("Error al buscar el último ID: " + e.getMessage());
            }

            // Recorremos cada producto de la factura: descontamos inventario y registramos la venta
            for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                String nombreProducto = modeloTabla.getValueAt(i, 0).toString(); // Columna 0: Nombre
                int cantidadVendida = Integer.parseInt(modeloTabla.getValueAt(i, 2).toString()); // Columna 2: Cantidad

                // Descontamos del inventario
                String sql = "UPDATE productos SET cantidad = cantidad - ? WHERE nombre = ?";
                java.sql.PreparedStatement pst = conexion.prepareStatement(sql);
                
                pst.setInt(1, cantidadVendida);
                pst.setString(2, nombreProducto);
                
                pst.executeUpdate();
                
                // Insertamos el ítem en la tabla de ventas con su factura correspondiente    
                String sqlVenta = "INSERT INTO ventas (id_factura, producto, cantidad, subtotal, fecha) VALUES (?, ?, ?, ?, NOW())"; 
                java.sql.PreparedStatement pstVenta = conexion.prepareStatement(sqlVenta);
                double subtotalFila = Double.parseDouble(modeloTabla.getValueAt(i, 3).toString());

                pstVenta.setInt(1, idFacturaUnico);
                pstVenta.setString(2, nombreProducto);
                pstVenta.setInt(3, cantidadVendida);
                pstVenta.setDouble(4, subtotalFila);

                pstVenta.executeUpdate(); 
                pstVenta.close();
                         
                pst.close();
            }
            
  
            // Enviamos una comanda a cocina como registro de la venta cobrada
            try {
                String detallePedido = "";
                for (int j = 0; j < modeloTabla.getRowCount(); j++) {
                    String cant = modeloTabla.getValueAt(j, 2).toString();
                    String prod = modeloTabla.getValueAt(j, 0).toString();
                    detallePedido += cant + "x " + prod + "\n"; // Quedará como "2x Café"
                }

                // Si el pedido viene de una mesa usamos su nombre; si no, marcamos "Caja Principal"
                String origenPedido = "Caja Principal";
                
                if (botonMesaActual != null) {
                    
                    origenPedido = this.getTitle();
                }

                String sqlComanda = "INSERT INTO comandas (mesa, detalle, estado) VALUES (?, ?, 'PENDIENTE')";
                java.sql.PreparedStatement pstComanda = conexion.prepareStatement(sqlComanda);
                pstComanda.setString(1, origenPedido);
                pstComanda.setString(2, detallePedido);
                pstComanda.executeUpdate();
                pstComanda.close();
                
            } catch (Exception e) {
                System.out.println("Error al enviar comanda a la cocina: " + e.getMessage());
            }
            
            javax.swing.JOptionPane.showMessageDialog(this, "Registrado con éxito, inventario actualizado.");
            
            // Generamos el ticket en PDF y lo abrimos automáticamente
            try {
                // Crea el documento PDF
                com.itextpdf.text.Document documento = new com.itextpdf.text.Document();
                String nombreArchivo = "Ticket_" + idFacturaUnico + ".pdf";
                com.itextpdf.text.pdf.PdfWriter.getInstance(documento, new java.io.FileOutputStream(nombreArchivo));

                documento.open();

                // Dibuja el encabezado del ticket
                documento.add(new com.itextpdf.text.Paragraph("========================================"));
                documento.add(new com.itextpdf.text.Paragraph("            MI RAQUELITA CAFÉ           "));
                documento.add(new com.itextpdf.text.Paragraph("========================================"));
                documento.add(new com.itextpdf.text.Paragraph("Factura #: " + idFacturaUnico));
                documento.add(new com.itextpdf.text.Paragraph("Fecha: " + new java.util.Date().toString()));
                documento.add(new com.itextpdf.text.Paragraph("----------------------------------------"));
                documento.add(new com.itextpdf.text.Paragraph("CANT  PRODUCTO                SUBTOTAL"));
                documento.add(new com.itextpdf.text.Paragraph("----------------------------------------"));

                double totalTicket = 0;
                
                // Recorre la tabla del pedido
                for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                    String prod = modeloTabla.getValueAt(i, 0).toString();
                    String cant = modeloTabla.getValueAt(i, 2).toString();
                    String sub = modeloTabla.getValueAt(i, 3).toString();
                    
                    totalTicket += Double.parseDouble(sub);

                    documento.add(new com.itextpdf.text.Paragraph(cant + " x " + prod + "  ->  $ " + sub));
                }

                // Pie de página y totales
                documento.add(new com.itextpdf.text.Paragraph("----------------------------------------"));
                documento.add(new com.itextpdf.text.Paragraph("TOTAL A PAGAR:          $ " + totalTicket));
                documento.add(new com.itextpdf.text.Paragraph("========================================"));
                documento.add(new com.itextpdf.text.Paragraph("       ¡Gracias por su compra!          "));
                documento.add(new com.itextpdf.text.Paragraph("========================================"));
                documento.close(); 
                
                java.awt.Desktop.getDesktop().open(new java.io.File(nombreArchivo));
                
            } catch (Exception e) {
                System.out.println("Error al crear el ticket PDF: " + e.getMessage());
            }

            // Limpiamos la pantalla para el siguiente cliente
            modeloTabla.setRowCount(0);
            jLabel1.setText("TOTAL: $ 0");
            
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al procesar la venta: " + e.toString());
        }
        
        // Si el pedido venía de una mesa, la liberamos y borramos su historial temporal
         if (botonMesaActual != null) {
             botonMesaActual.setBackground(java.awt.Color.GREEN); // La volvemos a poner Libre

             try {
                 conexion.ConexionDB con2 = new conexion.ConexionDB();
                 java.sql.Connection conexion2 = con2.establecerConexion();
                 String sqlLimpiar = "DELETE FROM pedidos_temporales WHERE mesa = ?";
                 java.sql.PreparedStatement pstLimpiar = conexion2.prepareStatement(sqlLimpiar);
                 pstLimpiar.setString(1, this.getTitle());
                 pstLimpiar.executeUpdate();
                 pstLimpiar.close();
             } catch (Exception exLimpiar) {
                 System.out.println("Error al limpiar memoria de la mesa: " + exLimpiar.getMessage());
             }

             this.dispose();
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.dispose();

        
        if (this.botonMesaActual != null) {
            // Si venimos de una mesa, traemos la pantalla de mesas al frente
            for (java.awt.Window ventana : java.awt.Window.getWindows()) {
                if (ventana instanceof PantallaMesas) {
                    ventana.setVisible(true);
                    ventana.toFront();
                    break;
                }
            }
        } else {
            // Si venimos del menú principal, lo buscamos y lo mostramos
            boolean menuEncontrado = false;
            for (java.awt.Window ventana : java.awt.Window.getWindows()) {
                if (ventana instanceof PantallaPrincipa) {
                    ventana.setVisible(true);
                    ventana.toFront();
                    menuEncontrado = true;
                    break;
                }
            }
            // Si el menú estaba cerrado, creamos una nueva instancia
            if (!menuEncontrado) {
                new PantallaPrincipa().setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Envio de comanda a cocina y abrir ticket
        try {
            javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            if (modeloTabla.getRowCount() == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay productos para enviar a la cocina.");
                return;
            }

            // Construimos el detalle del pedido como texto plano
            String detallePedido = "";
            for (int j = 0; j < modeloTabla.getRowCount(); j++) {
                String cant = modeloTabla.getValueAt(j, 2).toString();
                String prod = modeloTabla.getValueAt(j, 0).toString();
                detallePedido += cant + "x " + prod + "\n"; 
            }

            String origenPedido = "Caja Principal"; 
            if (botonMesaActual != null) {
                origenPedido = this.getTitle(); 
            }

            // Insertamos la comanda y recuperamos el ID generado por la base de datos
            conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();
            
            String sqlComanda = "INSERT INTO comandas (mesa, detalle, estado) VALUES (?, ?, 'PENDIENTE')";
            java.sql.PreparedStatement pstComanda = conexion.prepareStatement(sqlComanda, java.sql.Statement.RETURN_GENERATED_KEYS);
            pstComanda.setString(1, origenPedido);
            pstComanda.setString(2, detallePedido);
            pstComanda.executeUpdate();
            
            int idGenerado = 0;
            java.sql.ResultSet rsComanda = pstComanda.getGeneratedKeys();
            if(rsComanda.next()){ idGenerado = rsComanda.getInt(1); }
            
            pstComanda.close();
            

            // Contamos cuántos tickets de cocina ya están abiertos para posicionar el nuevo
            int ticketsAbiertos = 1;
            for (java.awt.Window ventana : java.awt.Window.getWindows()) {
                if (ventana instanceof PantallaComandas && ventana.isVisible()) {
                    ticketsAbiertos++;
                }
            }
            
            // Lanzamos la ventana de comanda con los datos del pedido
            PantallaComandas ticket = new PantallaComandas(idGenerado, origenPedido, detallePedido, ticketsAbiertos);
            ticket.setVisible(true);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Pedido enviado a la cocina");
            
        } catch (Exception e) {
            System.out.println("Error al enviar comanda: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaVentas().setVisible(true));
    }
    
    // Método para cargar la memoria de la mesa
    public void cargarPedidoMesa(String nombreMesa) {
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modeloTabla.setRowCount(0);
        double totalFactura = 0;

        try {
            conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();
            
            // Traemos todos los productos asociados a esta mesa
            String sql = "SELECT producto, precio, cantidad, subtotal FROM pedidos_temporales WHERE mesa = ?";
            java.sql.PreparedStatement pst = conexion.prepareStatement(sql);
            pst.setString(1, nombreMesa);
            java.sql.ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String prod = rs.getString("producto");
                double precio = rs.getDouble("precio");
                int cant = rs.getInt("cantidad");
                double sub = rs.getDouble("subtotal");
                
                modeloTabla.addRow(new Object[]{prod, precio, cant, sub});
                totalFactura += sub;
            }
            
            jLabel1.setText("TOTAL: $ " + totalFactura);
            pst.close();
            
        } catch (Exception e) {
            System.out.println("Error al cargar la memoria de la mesa: " + e.getMessage());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
