/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import conexion.ConexionDB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class PantallaReportes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaReportes.class.getName());

    /**
     * Creates new form PantallaReportes
     */
    public PantallaReportes() {
        initComponents();
        cargarHistorialVentas("Hoy");
        
        // Al recuperar el foco la ventana recarga el historial con el filtro activo,
        // así los datos siempre están actualizados al volver desde otra pantalla.
        this.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            @Override
            public void windowGainedFocus(java.awt.event.WindowEvent e) {
                // Lee qué filtro tienes seleccionado actualmente (Hoy, Todo, etc.) y recarga
                String seleccionado = comboFiltro.getSelectedItem().toString();
                cargarHistorialVentas(seleccionado);
            }

            @Override
            public void windowLostFocus(java.awt.event.WindowEvent e) {
                // No se requiere acción al perder el foco
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboFiltro = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("VENTAS TOTALES DEL DÍA");

        jLabel2.setText("TOTAL RECAUDADO: $ 0");

        comboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoy", "Última Semana", "Último Mes", "Todo" }));
        comboFiltro.addActionListener(this::comboFiltroActionPerformed);

        jButton2.setText("Volver al Menú");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(362, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltroActionPerformed
        // Cada vez que el usuario cambia el filtro, recargamos el historial con el rango elegido
        String seleccionado = comboFiltro.getSelectedItem().toString();
        cargarHistorialVentas(seleccionado);
    }//GEN-LAST:event_comboFiltroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();

        // Buscamos si el menú principal ya está abierto para no crear una instancia duplicada
        boolean menuEncontrado = false;
        for (java.awt.Window ventana : java.awt.Window.getWindows()) {
            if (ventana instanceof PantallaPrincipa) {
                ventana.setVisible(true); 
                ventana.toFront();
                menuEncontrado = true;
                break;
            }
        }

        // Si el menú no estaba abierto por algún motivo, lo creamos
        if (!menuEncontrado) {
            new PantallaPrincipa().setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaReportes().setVisible(true));
    }

    public void cargarHistorialVentas(String filtro) {
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // Limpiamos la tabla
        modelo.setColumnIdentifiers(new String[]{"Turno y Factura", "Responsable", "Productos", "Total ($)", "Fecha Exacta"});
        
        String condicionFecha = "";

        // Construimos el fragmento WHERE según el período seleccionado
        switch (filtro) {
            case "Hoy":
                condicionFecha = " WHERE DATE(v.fecha) = CURDATE() ";
                break;
            case "Última Semana":
                condicionFecha = " WHERE v.fecha >= DATE_SUB(CURDATE(), INTERVAL 7 DAY) ";
                break;
            case "Último Mes":
                condicionFecha = " WHERE v.fecha >= DATE_SUB(CURDATE(), INTERVAL 30 DAY) ";
                break;
            default: // "Todo"
                condicionFecha = ""; 
                break;
        }

        // Consulta principal: agrupa por factura y la relaciona con el turno de caja activo en ese momento.
        // El LEFT JOIN con caja_diaria permite identificar qué cajero atendió cada venta.
        String sql = "SELECT v.id_factura, "                                                                 // Columna 1
                   + "GROUP_CONCAT(CONCAT(v.producto, ' (', v.cantidad, ')') SEPARATOR ' + ') AS lista_productos, " // Columna 2
                   + "SUM(v.subtotal) AS total_venta, "                                                      // Columna 3
                   + "MAX(v.fecha) AS hora_venta, "                                                          // Columna 4
                   + "IFNULL(c.id, 0) AS numero_turno, "                                                     // Columna 5
                   + "IFNULL(c.cajero, 'Sin asignar') AS nombre_cajero "                                     // Columna 6 
                   + "FROM ventas v " 
                   + "LEFT JOIN caja_diaria c ON v.fecha >= c.fecha_apertura AND (v.fecha <= c.fecha_cierre OR c.fecha_cierre IS NULL) "
                   + condicionFecha 
                   + " GROUP BY v.id_factura, c.id, c.cajero "
                   + " ORDER BY numero_turno DESC, v.id_factura DESC";

        double totalRecaudado = 0;

        try (
            //Hacemos uso de try con recursos, para que java cierre la conexion automáticamente.    
            java.sql.Connection conexion = new conexion.ConexionDB().establecerConexion();
            java.sql.Statement st       = conexion.createStatement();
            java.sql.ResultSet rs       = st.executeQuery(sql)
        ) {

            while (rs.next()) {
                Object[] fila = new Object[5]; // Son 5 columnas visuales en la tabla
                
                int turno = rs.getInt("numero_turno");
                int factura = rs.getInt("id_factura");
                
                // Columna 0: Turno y Factura
                if (turno == 0) {
                    fila[0] = "Fac #" + factura + " (Prueba)"; 
                } else {
                    fila[0] = "Turno " + turno + " - Fac #" + factura;
                }
                
                // Si no hay turno asociado, marcamos la venta como prueba para distinguirla fácilmente
                fila[1] = rs.getString("nombre_cajero"); 
                
                // Las demás columnas...
                fila[2] = rs.getString("lista_productos");
                fila[3] = rs.getDouble("total_venta");
                fila[4] = rs.getTimestamp("hora_venta");
                
                totalRecaudado += rs.getDouble("total_venta");
                modelo.addRow(fila);
            }
            
            jLabel2.setText("TOTAL RECAUDADO: $ " + totalRecaudado);
            
        } catch (Exception e) {
            jLabel2.setText("Error al cargar el historial.");
            System.out.println("Error al cargar ventas por turno: " + e.getMessage());
        }
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
