/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Administrador
 */
public class PantallaInventario extends javax.swing.JFrame {
    // 1. CREAMOS LA VARIABLE: Aquí le decimos a la pantalla que usará el controlador
    private final controlador.ControladorInventario miControlador;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaInventario.class.getName());

    /**
     * Creates new form PantallaInventario
     */
    
    public PantallaInventario() {
        initComponents();
        
        // 2. INICIALIZAMOS EL CEREBRO: Apenas se abre la ventana, el controlador cobra vida
        miControlador = new controlador.ControladorInventario();
        
        // 3. LA ORDEN DE MEMORIA: Le decimos que pinte la tabla apenas nazca la ventana
        cargarTabla();
    }

    // Esto es lo que le enseña a la tabla a leer el cerebro ---
    private void cargarTabla() {
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        
        // 1. Limpiamos la tabla visual para que no se duplique lo viejo con lo nuevo
        modeloTabla.setRowCount(0);
        
        // 2. Un ciclo "For": Recorremos el cerebro y por cada producto que haya...
        for (modelo.Producto prod : miControlador.obtenerTodosLosProductos()) {
            
            // ...lo agregamos como una fila nueva en la tabla
            modeloTabla.addRow(new Object[]{
                prod.getId(), 
                prod.getNombre(), 
                prod.getCategoria(), 
                prod.getPrecio(), 
                prod.getCantidad()
            });
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Gestión de Inventario");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CATEGORIA", "PRECIO", "CANTIDAD"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio");

        jLabel4.setText("Cantidad");

        jButton1.setText("Agregar Producto");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Volver al Menú");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel5.setText("Categoria:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebidas Calientes", "Bebidas frias", "Comidas", "Entradas", "Postres", "Licores" }));

        jButton3.setText("Modificar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Eliminar");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jLabel6.setText("Buscar Producto");

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(119, 119, 119)
                                        .addComponent(jLabel3)
                                        .addGap(112, 112, 112)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 1. Cerramos la ventana en la que estamos parados actualmente
        this.dispose();

        // 2. Buscamos en la memoria si el Menú Principal ya está abierto
        boolean menuEncontrado = false;
        for (java.awt.Window ventana : java.awt.Window.getWindows()) {
            if (ventana instanceof PantallaPrincipa) {
                ventana.setVisible(true); // Lo hacemos visible
                ventana.toFront();        // Lo traemos al frente de la pantalla
                menuEncontrado = true;
                break; // Detenemos la búsqueda
            }
        }

        // 3. Medida de seguridad: Si por algún error no estaba abierto, creamos uno
        if (!menuEncontrado) {
            new PantallaPrincipa().setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // ESCUDO 1: Verificar que no haya campos vacíos
        if (jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty()) {
            // Si algún campo está vacío, sacamos una alerta en pantalla y detenemos todo
            javax.swing.JOptionPane.showMessageDialog(this, "¡Cuidado! Debes llenar todos los campos antes de guardar.", "Campos incompletos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Esta palabra mágica hace que el código se detenga aquí y no siga bajando
        }

        // ESCUDO 2: El bloque "Try-Catch" (Intentar y Atrapar)
        try {
            // INTENTAMOS hacer la conversión de texto a número y guardar el producto
            String nombre = jTextField1.getText();
            double precioFinal = Double.parseDouble(jTextField2.getText()); // Si hay letras aquí, Java lanza un error
            int cantidadFinal = Integer.parseInt(jTextField3.getText());    // Si hay letras aquí, Java lanza un error
            String categoria = jComboBox1.getSelectedItem().toString();

            int idGenerado = miControlador.obtenerTodosLosProductos().size() + 1;
            modelo.Producto nuevoProducto = new modelo.Producto(idGenerado, nombre, categoria, precioFinal, cantidadFinal);

            miControlador.agregarProducto(nuevoProducto);
            cargarTabla();

            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");

            // ¡ALERTA DE ÉXITO VISUAL! Reemplazamos el System.out por una ventana real
            javax.swing.JOptionPane.showMessageDialog(this, "¡Producto agregado con éxito a Mi Raquelita!", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException error) {
            // ATRAPAMOS el error: Si el usuario escribió letras en precio o cantidad, el programa no colapsa, sino que cae aquí.
            javax.swing.JOptionPane.showMessageDialog(this, "Error: El Precio y la Cantidad deben ser números válidos (sin letras ni espacios).", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
                                             
        // 1. Averiguamos a qué fila le diste clic
        int filaSeleccionada = jTable1.getSelectedRow();
        
        // 2. Si le diste clic a una fila válida (la primera fila es la 0)
        if (filaSeleccionada >= 0) {
            // Extraemos los datos de esa fila específica y los subimos a las cajas de texto
            
            // Columna 1 es Nombre
            jTextField1.setText(jTable1.getValueAt(filaSeleccionada, 1).toString()); 
            
            // Columna 2 es Categoría (Desplegable)
            jComboBox1.setSelectedItem(jTable1.getValueAt(filaSeleccionada, 2).toString());
            
            // Columna 3 es Precio
            jTextField2.setText(jTable1.getValueAt(filaSeleccionada, 3).toString()); 
            
            // Columna 4 es Cantidad
            jTextField3.setText(jTable1.getValueAt(filaSeleccionada, 4).toString()); 
        }
    
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                                              
        // 1. Verificamos que haya una fila seleccionada en la tabla
        int filaSeleccionada = jTable1.getSelectedRow();
        
        if (filaSeleccionada >= 0) {
            
            // ESCUDO 1: Verificar que no haya dejado campos vacíos al intentar modificar
            if (jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "¡Cuidado! No puedes dejar campos vacíos al modificar.", "Campos incompletos", javax.swing.JOptionPane.WARNING_MESSAGE);
                return; // Detiene la ejecución aquí para que no siga bajando y colapse
            }

            // ESCUDO 2: El bloque "Try-Catch" (Intentar y Atrapar)
            try {
                // Extraemos el ID del producto (que está oculto en la Columna 0 de la tabla)
                int idParaModificar = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
                
                // Capturamos los textos ya corregidos de las cajas
                String nombreCorregido = jTextField1.getText();
                double precioCorregido = Double.parseDouble(jTextField2.getText()); // Si hay letras, ¡el Catch lo atrapa!
                int cantidadCorregida = Integer.parseInt(jTextField3.getText());    // Si hay letras, ¡el Catch lo atrapa!
                String categoriaCorregida = jComboBox1.getSelectedItem().toString();
                
                // Mandamos la orden al Cerebro para actualizar la RAM
                miControlador.modificarProducto(idParaModificar, nombreCorregido, categoriaCorregida, precioCorregido, cantidadCorregida);
                
                // Recargamos la tabla visual para ver los cambios
                cargarTabla();
                
                // Limpiamos las cajas
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                
                // ¡Mensaje de Éxito Visual en ventana emergente!
                javax.swing.JOptionPane.showMessageDialog(this, "¡Producto modificado correctamente!", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
            } catch (NumberFormatException error) {
                // ATRAPAMOS el error si el usuario intentó guardar letras en lugar de números
                javax.swing.JOptionPane.showMessageDialog(this, "Error: El Precio y la Cantidad deben ser números válidos.", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
        } else {
            // Si presionó el botón modificar sin haber seleccionado ningún producto de la tabla
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor selecciona un producto de la tabla primero.", "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // 1. Verificamos que tengas una fila seleccionada en la tabla visualmente
        int filaSeleccionada = jTable1.getSelectedRow();
        
        if (filaSeleccionada >= 0) {
            // 2. Extraemos el ID del producto (siempre está escondido en la Columna 0 de la tabla)
            int idParaEliminar = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
            
            // 3. ¡LA MAGIA! Le mandamos la orden al Cerebro para que lo elimine de la RAM
            miControlador.eliminarProducto(idParaEliminar);
            
            // 4. Recargamos la tabla para que el producto desaparezca de la vista
            cargarTabla();
            
            // 5. Limpiamos las cajas por si habían quedado llenas con los datos de ese producto
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            
        } else {
            // Si le dio a eliminar sin haber seleccionado nada en la tabla
            System.out.println("Error: Por favor selecciona un producto de la tabla para eliminarlo.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // 1. Capturamos lo que el usuario está escribiendo en tiempo real
        String textoBuscado = jTextField4.getText(); // Cambia el 4 si tu cajita se llama diferente

        // 2. Extraemos el "modelo" de tu tabla (donde están los datos)
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        
        // 3. Creamos la herramienta mágica: El Filtro (Sorter)
        javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> clasificador = new javax.swing.table.TableRowSorter<>(modeloTabla);
        
        // 4. Le inyectamos el filtro a tu tabla visual
        jTable1.setRowSorter(clasificador);

        // 5. Aplicamos la regla de búsqueda
        if (textoBuscado.trim().length() == 0) {
            // Si la caja de búsqueda está vacía, mostramos todo (quitamos el filtro)
            clasificador.setRowFilter(null);
        } else {
            // Si hay texto, filtramos. El "(?i)" es un truco maestro para que ignore si escribes en MAYÚSCULAS o minúsculas.
            clasificador.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + textoBuscado));
        }
    }//GEN-LAST:event_jTextField4KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaInventario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
