/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Administrador
 */
public class PantallaMesas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaMesas.class.getName());

    /**
     * Creates new form PantallaMesas
     */
    public PantallaMesas() {
        initComponents();
        // 1. Escanea los colores al abrir la ventana por primera vez
        verificarEstadoMesas(); 

        // 2. EL VIGILANTE: Escanea cada vez que la ventana vuelva a estar al frente
        this.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            @Override
            public void windowGainedFocus(java.awt.event.WindowEvent e) {
                verificarEstadoMesas(); // Actualiza los colores al volver de la caja
            }
            @Override
            public void windowLostFocus(java.awt.event.WindowEvent e) {
                // No hacemos nada al perder el foco
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(51, 255, 0));
        jButton1.setText("Mesa 1");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(51, 255, 0));
        jButton2.setText("Mesa 2");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(51, 255, 0));
        jButton3.setText("Mesa 3");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(51, 255, 0));
        jButton4.setText("Mesa 4");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setBackground(new java.awt.Color(51, 255, 0));
        jButton5.setText("Mesa 5");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton9.setText("Volver al Menú");
        jButton9.addActionListener(this::jButton9ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(313, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // 1. Creamos una nueva caja registradora
     PantallaVentas caja = new PantallaVentas();
     // 2. Le mandamos este botón y su nombre para que los controle
     caja.configurarMesa(jButton1, "Mesa 1"); 
     // 3. Abrimos la ventana
     caja.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 1. Creamos una nueva caja registradora
        PantallaVentas caja = new PantallaVentas();
        // 2. Le mandamos el botón de la Mesa 2 y su nombre
        caja.configurarMesa(jButton2, "Mesa 2"); 
        // 3. Abrimos la ventana
        caja.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // 1. Creamos una nueva caja registradora
        PantallaVentas caja = new PantallaVentas();
        // 2. Le mandamos el botón de la Mesa 2 y su nombre
        caja.configurarMesa(jButton3, "Mesa 3"); 
        // 3. Abrimos la ventana
        caja.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // 1. Creamos una nueva caja registradora
        PantallaVentas caja = new PantallaVentas();
        // 2. Le mandamos el botón de la Mesa 2 y su nombre
        caja.configurarMesa(jButton4, "Mesa 4"); 
        // 3. Abrimos la ventana
        caja.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // 1. Creamos una nueva caja registradora
        PantallaVentas caja = new PantallaVentas();
        // 2. Le mandamos el botón de la Mesa 2 y su nombre
        caja.configurarMesa(jButton5, "Mesa 5"); 
        // 3. Abrimos la ventana
        caja.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // 1. Cerramos la ventana en la que estamos parados actualmente
        this.dispose();

        // 2. Buscamos en la memoria si el Menú Principal ya está abierto
        boolean menuEncontrado = false;
        for (java.awt.Window ventana : java.awt.Window.getWindows()) {
            if (ventana instanceof PantallaPrincipa) {
                ventana.setVisible(true); // Lo hacemos visible
                ventana.toFront();        // Lo traemos al frente de la pantalla
                menuEncontrado = true;
                break; // Detenemos la búsqueda
            }
        }

        // 3. Medida de seguridad: Si por algún error no estaba abierto, creamos uno
        if (!menuEncontrado) {
            new PantallaPrincipa().setVisible(true);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaMesas().setVisible(true));
    }

    // --- NUEVO: MÉTODO PARA ESCANEAR Y PINTAR LAS MESAS OCUPADAS ---
    public void verificarEstadoMesas() {
        // 1. Por precaución, pintamos todas de VERDE primero (Libres)
        jButton1.setBackground(java.awt.Color.GREEN); 
        jButton2.setBackground(java.awt.Color.GREEN); 
        jButton3.setBackground(java.awt.Color.GREEN); 
        jButton4.setBackground(java.awt.Color.GREEN); 
        jButton5.setBackground(java.awt.Color.GREEN); 
        // Si usas los botones 6, 7 y 8 después, descomenta estas líneas:
        // jButton6.setBackground(java.awt.Color.GREEN);
        // jButton7.setBackground(java.awt.Color.GREEN);
        // jButton8.setBackground(java.awt.Color.GREEN);

        try {
            conexion.ConexionDB con = new conexion.ConexionDB();
            java.sql.Connection conexion = con.establecerConexion();

            // 2. Le preguntamos a la base de datos: "¿Qué mesas tienen cuenta pendiente?"
            String sql = "SELECT DISTINCT mesa FROM pedidos_temporales";
            java.sql.PreparedStatement pst = conexion.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();

            // 3. Pintamos de ROJO las que salgan en la lista
            while (rs.next()) {
                String mesaOcupada = rs.getString("mesa");

                if (mesaOcupada.equals("Mesa 1")) { jButton1.setBackground(java.awt.Color.RED); }
                if (mesaOcupada.equals("Mesa 2")) { jButton2.setBackground(java.awt.Color.RED); }
                if (mesaOcupada.equals("Mesa 3")) { jButton3.setBackground(java.awt.Color.RED); }
                if (mesaOcupada.equals("Mesa 4")) { jButton4.setBackground(java.awt.Color.RED); }
                if (mesaOcupada.equals("Mesa 5")) { jButton5.setBackground(java.awt.Color.RED); }
                // Si agregas más mesas, pones aquí sus if correspondientes
            }

            pst.close();
            conexion.close(); 
            
        } catch (Exception e) {
            System.out.println("Error al verificar el estado de las mesas: " + e.getMessage());
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
